[tool.ruff]
# https://beta.ruff.rs/docs/rules/
select = [
    "E",    # pycodestyle (`E`)
    "F",    # Pyflakes (`F`)
    "C901", # McCabe complexity (`C901`)
    "W",    # pycodestyle warnings (`W`)
    "B",    # flake8-bugbear (`B`)
    "I001", # isort (sort import for type and alphanumerically),
    "N",    # pep8 naming
    "UP",   # pyupgrade
    "ANN",  # flake8 annotations
    "ASYNC",# flake8 async
    "S",    # bandit
    "FBT",  # boolean trap
    "A",    # flake8 shadowing builtins
    "COM",  # missing or extra commas
    "C4",   # flake8 comprehension
    "EM",   # better error messages check
    "G",    # logging format
    "INP",  # remove implicit namespace package
    "PIE",  # flake8 pie, unecessary statements or duplicates
    "T20",  # removes prints
    "PYI",  # Specializations for type hinting stub files
    "Q",    # quotes lint
    "RSE",  # raise linter uneccessary parenthesis
    "RET",  # return statement
    "SLF",  # accessing private members
    "SIM",  # simplifies code
    # "TCH",  # type check
    "ARG",  # unused arguments
    "PTH",  # use Path insead of os library
    "PLE",
    "PLR",
    "PLW",
    "TRY",  # prevents error handling antipatterns
    "FLY",
    "PERF", # check for performance antipatterns
    "RUF",  # ruff rules
]
ignore = [
    "ANN401",  # dynamically typed expression
    "B008",    # do not perform function calls Depends
    "ANN101",  # type annoation on self
    "ANN102",  # type annotation on cls
    "TD002",   # missing author in TODO
    "TD004",   # missing colon in TODO
    "TD003",   # missing link
    "TRY003",  # avoid long exception messages outside class
    "S324",    # sha1 is insecure (but BitTorrent uses it รง_รง)
    "PLR0913", # too many arguments in function definition
    "PERF203", # `try`-`except` within a loop incurs performance overhead
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
fix = false 
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "tests"
]
per-file-ignores = {}

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"

[tool.mypy]
python_version = "3.10"
plugins = []
exclude = [
  "tests"
] 
# follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true
no_implicit_reexport = true
warn_return_any = true
warn_unused_configs = true

# This at false, otherwise it will flag every generic obj like dict
disallow_any_generics = false

# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = true
